version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: pragma
      MONGO_INITDB_ROOT_PASSWORD: pragmamongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./data/assets:/data/db/assets
      - ./data/responsables:/data/db/responsables
    networks:
      - mongodb_network

networks:
  mongodb_network:
